adding new fields
bristlemouth/bm_protocol pull request #56
Opened 2023-11-29 22:50 UTC by russelldeguzman

2023-11-29 22:56 UTC, russelldeguzman commented on src/apps/bridge/aanderaaController.cpp
> +                              "%.3f,"        // temp_mean_deg_c
FYI @towynlin to update the header on the `AANDERAA_AGG.log` Spotter side

2023-11-30 17:49 UTC, towynlin requested changes
Looks great! Called out one small change related to tilt bounds.

2023-11-30 17:49 UTC, towynlin commented on src/apps/bridge/aanderaaController.cpp
> +              }
Max tilt is actually different — π/2 (that is, `M_PI_2` from math.h) instead of 2π.

2023-11-30 18:02 UTC, towynlin approved these changes

2023-11-30 18:09 UTC, merged